### ISSUE TITLE
Consider abstracting out `quotes.json`

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#107]
Maybe this could be pulled from an API

Maybe the `quotes.json` file could be made into an npm package?

Would be good for a first timer with reference to @amandeepmittal's [stoic-api](https://github.com/amandeepmittal/stoic-api) for reference?

**Comment by amandeepmittal** [comment]
Maybe we can create a separate npm package if the context of stoic-api does not fit here for every retweet.

**Comment by spences10** [comment]
I'm on it right now, seeing if there's an `npm` package already out there

This would be a good first issue, if I can find a suitable npm package I'll update the ticket with the details

**Comment by amandeepmittal** [comment]
Or if you merge quotes.json in stoic-api, be my guest.
