### ISSUE TITLE
Moar badges

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#111]
Add Prettier badge

Add in the Prettier badge in the readme:

Add this line below the license badge>

```
[![styled with prettier](https://img.shields.io/badge/styled_with-prettier-ff69b4.svg)](https://github.com/prettier/prettier)
```

For the badge to look like this: [![styled with prettier](https://img.shields.io/badge/styled_with-prettier-ff69b4.svg)](https://github.com/prettier/prettier)

Label it as a good first issue and help wanted @amandeepmittal please 

---

Also add in the Twitter follow intent button:

Adding the following HTML into the README.me

```html
<p>
  <a href="https://twitter.com/intent/follow?screen_name=_100DaysOfCode">
    <img src="https://img.shields.io/twitter/follow/shields_io.svg?style=social"
      alt="follow on Twitter"></a>
</p>
```
You will have a follow on Twitter badge:
<p>
  <a href="https://twitter.com/intent/follow?screen_name=_100DaysOfCode">
    <img src="https://img.shields.io/twitter/follow/_100DaysOfCode.svg?style=social"
      alt="follow on Twitter"></a>
</p>

**Comment by amandeepmittal** [comment]
Great issue! I have more in mind:
- Twitter Follower Count [![Twitter Follow](https://img.shields.io/twitter/follow/espadrine.svg?style=social&label=Follow)]()
- Github issues state [![GitHub issue state](https://img.shields.io/github/issues/detail/s/badges/shields/979.svg)]()
- Github PR(s) Count [![GitHub pull requests](https://img.shields.io/github/issues-pr/cdnjs/cdnjs.svg)]()

**Comment by spences10** [comment]
Ok, yes, I think there are issues with the issues badge however, and PR badge actually, if you wrap up the Twitter HTML follow intent in a `<p>` tag you can use the follow:

```html
<p>
  <a href="https://twitter.com/intent/follow?screen_name=_100DaysOfCode">
    <img src="https://img.shields.io/twitter/follow/shields_io.svg?style=social"
      alt="follow on Twitter"></a>
</p>
```
<p>
  <a href="https://twitter.com/intent/follow?screen_name=_100DaysOfCode">
    <img src="https://img.shields.io/twitter/follow/_100DaysOfCode.svg?style=social"
      alt="follow on Twitter"></a>
</p>

I'll add that to the ticket 👍

**Comment by amandeepmittal** [comment]
Also adding [Slack Channel](https://100xcode.slack.com) badge will be a good idea for future reference.

**Comment by mhaviv** [comment]
I'm on it! 👍

**Comment by amandeepmittal** [comment]
I am making a checklist of Badges we need here for brevity:
- [x] styled with prettier
- [x] 100Days Twitter Bot with Followers count
- [] Slack Channel
- [] Github PRs count
- [] Github issue count.

If you guys want to add anymore, let me know.

**Comment by mhaviv** [comment]
On it no problem! 👍 😊
