### ISSUE TITLE
Add Emojis in Tweet responders?

### ISSUE THREAD

**Issue by amandeepmittal** [freeCodeCamp/100DaysOfCode-twitter-bot#117]
@spences10 what do you think? A collection of emoticons with random tweets or one emoji for an individual tweet? 😀😁

**Comment by spences10** [comment]
What context is it around? I've done it before with an array of emoji what you appended to the end of the tweet

**Comment by amandeepmittal** [comment]
The context I am proposing are the "welcome" tweets. As they have different welcome message, so I thought adding an emoji with the tweet will be a good idea.

**Comment by spences10** [comment]
You have an example of what you have in mind?

**Comment by amandeepmittal** [comment]
Adding an emoji to tweets like these: 
![screen shot 2018-01-09 at 10 50 11 am](https://user-images.githubusercontent.com/10234615/34706081-f90196d8-f52a-11e7-9d57-027f3d2ef6e8.png)

**Comment by spences10** [comment]
Ok, lets go with:

['👍', '👌', '❤️','☕️','🍕','✨','🦄']
