### ISSUE TITLE
Consider adding development branch

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#122]
Please consider adding a development branch and possibly a branch for adding patches to

Also please consider adding the following protection on branches `master`, `development` and `patch` so they are protected:

![image](https://user-images.githubusercontent.com/234708/37251878-f82119a4-250f-11e8-92c0-62250e0312d8.png)

Thanks

**Comment by amandeepmittal** [comment]
Thanks @spences10 Will look into it and do the required implementations.

**Comment by amandeepmittal** [comment]
Yes, that is the reason.

**Comment by QuincyLarson** [comment]
@amandeepmittal I've granted you full admin privileges for this project (I hadn't realized you didn't have them).

Feel free to create any branches or configurations you see necessary. Let me know if I can do anything to help :)

**Comment by amandeepmittal** [comment]
Thanks @QuincyLarson! 
@spences10 will update the branch as per your instructions over the weekend.

**Comment by spences10** [comment]
Cool, just to expand on the patch branch, it's how I have been managing dependency updates, I merge them into there then if there are any failures (failed Travis build) then the dev/master branches are not affected

**Comment by spences10** [comment]
I'l like to help maintain this too if that's ok with you @QuincyLarson and @amandeepmittal 🙏 

I've contributed quite a lot to this project and would be happy to help maintain it.

**Comment by amandeepmittal** [comment]
Ofcourse @spences10. You are the biggest contributor to thos project. @QuincyLarson can we give him the rights and add him as a maintainer?

**Comment by QuincyLarson** [comment]
@spences10 I've granted you admin access as well :)

**Comment by spences10** [comment]
Wheeeee! Thanks @QuincyLarson 🙏

**Comment by spences10** [comment]
This can be closed now, I have done all the admin

@amandeepmittal do you know any good CI tools for Heroku?

**Comment by amandeepmittal** [comment]
Travis.
