### ISSUE TITLE
Practice bot

### ISSUE THREAD

**Issue by danoloo** [freeCodeCamp/100DaysOfCode-twitter-bot#148]

**Comment by spences10** [comment]
Hey @danoloo 

Care to give any more detail on the issue over the title?

I'll leave this open for today and close it if you are unable to add anything to the issue description.

Many thanks 🙏

**Comment by danoloo** [comment]
> Hey @danoloo 
> 
> Care to give any more detail on the issue over the title?
> 
> I'll leave this open for today and close it if you are unable to add anything to the issue description.
> 
> Many thanks 🙏

Thanks for response, new to GitHub and on my first day, I'll remove it for now. Thanks for your assistance.

**Comment by spences10** [comment]
No problem, reach out if you need any help @amandeepmittal and I are both around on Twitter 👍
