### ISSUE TITLE
config.js to be included in .gitignore 

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#20]
Just a thought that the Twitter keys for this are regenerated and kept private so that someone with not the best intentions could post what they like?

As it stands anyone can take this code and post what they like to the @_100DaysOfCode account on Twitter

**Comment by amandeepmittal** [comment]
Yes, that's true and thanks for the reminder. But currently where I have deployed this application, it takes code directly from Github. I'll be switching it soon.

**Comment by spences10** [comment]
I have done this for my other bot as I only really noticed it was an issue when there were several of us all tweeting from the same account :+1:

**Comment by spences10** [comment]
Maybe the keys are shared via [keybase.io](https://keybase.io/)?

Example here from the site...

```
# view someone else's signed files
cd /keybase/public/chris
cat plan.txt

# your encrypted, private directory
cd /keybase/private/spences10
echo "I have a secret" > diary.txt

# your public, signed directory
cd /keybase/public/spences10
echo "This is signed." > a_contract_with_the_world.txt

# an encrypted end-to-end directory with a friend
cd /keybase/private/spences10,chris
echo "Wicked." > awes.txt
```

**Comment by spences10** [comment]
Didn't mean to close! Apologies!

**Comment by spences10** [comment]
@amandeepmittal this can be closed now that we have a workaround for the keys now :+1:
