### ISSUE TITLE
The Bot is twiting two times for the same person

### ISSUE THREAD

**Issue by Ilyes-Hammadi** [freeCodeCamp/100DaysOfCode-twitter-bot#22]
I noticed that the Bot is twiting two time for the same person.

**Comment by amandeepmittal** [comment]
@Ilyes-Hammadi in what scenario?

**Comment by Ilyes-Hammadi** [comment]
@amandeepmittal when detecting a Negative tweet (Sentiment detection), it's tweeting two times for the same person.

**Comment by stephanie56** [comment]
@Ilyes-Hammadi is that a same tweet goes to the same person?

**Comment by Ilyes-Hammadi** [comment]
@stephanie56 it's tweeting two different tweet each times

**Comment by amandeepmittal** [comment]
@Ilyes-Hammadi have you find the cause?

**Comment by spences10** [comment]
Someone left the keys in the ignition :smile:
