### ISSUE TITLE
Bot replies to re-tweets.

### ISSUE THREAD

**Issue by raisedadead** [freeCodeCamp/100DaysOfCode-twitter-bot#24]
I re-tweeted one user:
https://twitter.com/heyamberwilkie/status/818507978697506818

![image](https://cloud.githubusercontent.com/assets/1884376/21879361/52845536-d8be-11e6-966b-b08af1e50b41.png)

And the bot replied to me think that I am on my first day of streak
https://twitter.com/_100DaysOfCode/status/818512348080115713

![image](https://cloud.githubusercontent.com/assets/1884376/21879390/8c2dc5e2-d8be-11e6-8462-f1f85e147881.png)

And it kept up the conversation:
https://twitter.com/_100DaysOfCode/status/818512644994985984

**Comment by amandeepmittal** [comment]
@raisedadead thank you for notifying, will look into it.

**Comment by spences10** [comment]
Maybe [this](9c9b83b09bb55f77660c868b7d52ae3bff31b20b) can be used here for this?

It should rule out the majority of replies and RTs, right @amandeepmittal?
