### ISSUE TITLE
Whenever someone hits 100 days, tweet out a congratulations

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/100DaysOfCode-twitter-bot#3]

**Comment by abhijeetpanda12** [comment]
I can work on this issue, but it may take time, I am in a learning phase and I believe I'll complete the project if given the chance.

**Comment by amandeepmittal** [comment]
@abhijeetpanda12 looking forward to your PR

**Comment by abhijeetpanda12** [comment]
@amandeepmittal  could you provide me some help for things that you think I need to take care of?

**Comment by amandeepmittal** [comment]
To get a basic idea you can get familiar with the `bot.js` file itself. The code has comments which might help you. You can check out some articles on Twitter Bots and Node.js if you are not famiilar with them. Or you can straight away dive into [`twit`](https://www.npmjs.com/package/twit) documentation.

**Comment by abhijeetpanda12** [comment]
@amandeepmittal thank you very much. I am looking into it. I'll keep posted.

**Comment by amandeepmittal** [comment]
solved by PR #8
