### ISSUE TITLE
Add Additional Hash Tags to Tweets

### ISSUE THREAD

**Issue by benjaminspak** [freeCodeCamp/100DaysOfCode-twitter-bot#37]
I would like to add #301DaysOfCode to tweets so people following that track can join part of the larger FCC community.

**Comment by spences10** [comment]
What branch are you doing this under @benjaminspak?

**Comment by benjaminspak** [comment]
@spences10 Haven't worked on a branch for it. I spoke with @amandeepmittal and he mentioned he needed to speak with the other project members about it before we moved forward.

**Comment by spences10** [comment]
Ok coolio, so waiting to hear back from @amandeepmittal

**Comment by amandeepmittal** [comment]
I think we can update it with #301DaysOfCode hashtags. @benjaminspak you should do it. Make yourself familiar to code and add the necessary hashtag.

**Comment by amandeepmittal** [comment]
@benjaminspak merged: #44. This issue can be closed now.
