### ISSUE TITLE
Standardise call timers 

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#39]
So as I understand it, 100DoC bot is calling functions in two differing ways which seem the samey 

```
setImmediate(checkIfFirstOrLastDay, 720000);
```

[bot.js#L148](https://github.com/freeCodeCamp/100DaysOfCode-twitter-bot/blob/master/bot.js#L148)

And 

```
setInterval(favoriteTweet, 960000);
```

[bot.js#L93](https://github.com/freeCodeCamp/100DaysOfCode-twitter-bot/blob/master/bot.js#L93)

and I'm asking for clarification here just as much as agreement but, is there not one way we could agree to use just one for consistency?

and also I have no idea what 960000 and 720000 milliseconds are and have to go convert them

can we agree on the 

```
setInterval(favoriteTweet, 1000 * 60 * howeverManayMinutes);
```

So anyone reading can quickly see how long the interval is?

Thanks.

**Comment by amandeepmittal** [comment]
@spences10 `setInterval` serves it own purposes, but the reason I used `setImmediate` [is this](http://stackoverflow.com/questions/24117267/nodejs-settimeoutfn-0-vs-setimmediatefn). You will find your answer. 👍

**Comment by spences10** [comment]
Ok, cool can we agree on the interval format? I find it easier to read `1000 * 60 * 16` as 16 minutes rather than `960000`

**Comment by amandeepmittal** [comment]
Sure.
