### ISSUE TITLE
Whenever someone starts day 1, tweet an encouraging message to them

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/100DaysOfCode-twitter-bot#4]

**Comment by spences10** [comment]
This and [#3](https://github.com/FreeCodeCamp/100DaysOfCode-twitter-bot/issues/3) are pretty similar, could they not be done as the same change? 

Happy to do both by the way 👍

**Comment by amandeepmittal** [comment]
Yes they'll have similar functionality and you can use a single PR to solve these issues. Just mention in the PR, which issues you have solved.

**Comment by amandeepmittal** [comment]
solved by PR #8
