### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#49]
Licence it's MIT, right?

![image](https://cloud.githubusercontent.com/assets/234708/22522879/2d9982d0-e8b5-11e6-9e15-4292cab8715a.png)

![image](https://cloud.githubusercontent.com/assets/234708/22522890/3913f21c-e8b5-11e6-9555-0e943dff8101.png)

**Comment by amandeepmittal** [comment]
Nope, it's BSD 3-Clause.

**Comment by spences10** [comment]
Better close the ticket then :blush:
