### ISSUE TITLE
If a #100DaysOfCode tweet has negative sentiment, tweet back encouragement

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/100DaysOfCode-twitter-bot#5]

**Comment by spences10** [comment]
I've been playing around with the `twit` package and getting to grips with it so happy to take a look at this too, but think [#3](https://github.com/FreeCodeCamp/100DaysOfCode-twitter-bot/issues/3) and [#4](https://github.com/FreeCodeCamp/100DaysOfCode-twitter-bot/issues/4) could be done first, maybe?

**Comment by Ilyes-Hammadi** [comment]
I've started to implement the sentiment detection in the chat bot using the [Sentiment 3 API](https://market.mashape.com/vivekn/sentiment-3) and i need help for the responses, i need examples of responses in case of a Negative, Positive and Neutral sentiment.

**Comment by QuincyLarson** [comment]
@Ilyes-Hammadi This is awesome! @ka11away do you have any suggestions for the messages? 

I'm going to tweet this out to get some ideas for encouraging words from people following me on Twitter.

**Comment by amandeepmittal** [comment]
@QuincyLarson are you looking for messages/encouraging words?

**Comment by QuincyLarson** [comment]
Did I mention we have suggestions? 😄 

https://twitter.com/ossia/status/817982177547878400

**Comment by QuincyLarson** [comment]
@amandeepmittal @Ilyes-Hammadi @spences10 

Did I mention we have suggestions? 😄

https://twitter.com/ossia/status/817982177547878400

**Comment by Ilyes-Hammadi** [comment]
@QuincyLarson thanks to you and your followers for the help, it's just awesome how people are helpful 😄. I've added the proposed quotes with the [existing one](https://github.com/FreeCodeCamp/100DaysOfCode-twitter-bot/pull/10/commits/45482008ebabdf59a1174823cfdf52cb8faeaa60).

**Comment by QuincyLarson** [comment]
@Ilyes-Hammadi awesome! This is a solid list! Thank you for doing this!

**Comment by amandeepmittal** [comment]
This has been solved by and the PR is merged now. Thanks to @Ilyes-Hammadi. I think we can close this issue, @QuincyLarson ?

**Comment by benjaminspak** [comment]
@QuincyLarson @amandeepmittal I added more quotes ^_^

**Comment by amandeepmittal** [comment]
@QuincyLarson I think this task is done. Can we close this issue now?
