### ISSUE TITLE
Keys left in ignition

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#54]
API keys in `config.js` again, I have submitted PR to use `.env` `require('dotenv')` so API keys can be ignored in future :smile: 

Added #53 for this

**Comment by amandeepmittal** [comment]
Yes, and the app is deployed directly from this repo. I will moving everything locally on the deployment site soon.

**Comment by spences10** [comment]
Ok, but for people wanting to fork and make their own changes do you think that using `dotenv` will be useful?

**Comment by amandeepmittal** [comment]
@spences10 They will have to generate their own keys and tokens. Create a sample app to test the functionality they want to implement in this repo and if everything works, they can then make a fork for same functionality. What do you think of this path?

**Comment by spences10** [comment]
Yes that is the intention, I think I mentioned it before in a previous issue but without this PR, this PR it's intended that the user set up their own keys/bot/etc

**Comment by amandeepmittal** [comment]
Twit module is unable to read env vars when I am using `dotenv` module. 
![See This:](http://i.imgur.com/rZyYe0H.png)

**Comment by spences10** [comment]
Ok cool, so you have the API keys in the `.env` file and they're _not_ surrounded by `''` is that right?

**Comment by amandeepmittal** [comment]
Now since I revoked the access of this repo form heroku account, this has created a problem. This same repo cannot be deployed back since I do not have access to the freeCodeCamp org. @QuincyLarson  can we do something about this? Can we give heroku access to this repo again?

**Comment by QuincyLarson** [comment]
@amandeepmittal I am not 100% what you're asking. Whose Heroku account is this app running on? Why does Heroku need access to a specific repo? Can't you just deploy the code from this repo to Heroku? Does this have to do with the Heroku project's own environment variables?

**Comment by amandeepmittal** [comment]
@QuincyLarson Before transferring this repo to freeCodeCamp, my Heroku account had direct access to it for deployment purposes. Since, this repo has been transferred, I am unable to deploy it directly to Heroku.

However, I am deploying a clone of this repo. If you have no problem with that, then it's fine with me.

PS: No, the environment variables is another matter.

**Comment by spences10** [comment]
@amandeepmittal was it the changes in #53 that caused the issue?

I notice it was rejected, was that because it broke the build or because that isn't how you want to implement the solution to people posting their private Twitter API keys to GitHub?

**Comment by amandeepmittal** [comment]
Yes, it broke the build. The Twit module cannot read environment variables' values. See the screen shot (above ꜛꜛꜛ)

**Comment by spences10** [comment]
The `twit` module can read the vars in the versions I have used it with my friend, I tested this several times with the `twitter-bot-bootstrap` and my own version of the `100DoC twitter bot`

**Comment by amandeepmittal** [comment]
Strange. What `dotenv` version are you using? I am using 2.0.0

**Comment by spences10** [comment]
`"dotenv": "^4.0.0",` 👍

**Comment by amandeepmittal** [comment]
Okay, let me try with that.

**Comment by amandeepmittal** [comment]
@spences10 can you please make a PR again?

**Comment by spences10** [comment]
Sure, I think I deleted my branch but it shouldn't take long to implement again.

PR incoming 👍

**Comment by spences10** [comment]
Submitted #56

**Comment by spences10** [comment]
#56 merged, so close, thanks all :+1:
