### ISSUE TITLE
User blacklist enhance

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#57]
Consider adding `SuperCoderBot` @heroes_bot to the user blacklist

Maybe add blacklisted usernames to the `config.js` files like in the example done for the [twitter bot bootstrap](https://github.com/spences10/twitter-bot-bootstrap/commit/37d24ca83845e9a173848741387ced12f54bddff)

![image](https://cloud.githubusercontent.com/assets/234708/23119411/0ac0a050-f750-11e6-861b-d6d2f83a067a.png)

**Comment by amandeepmittal** [comment]
@spences10 Will you make that PR?

**Comment by spences10** [comment]
Errem, I'll take a looksee 👍

**Comment by spences10** [comment]
@amandeepmittal I have done some work on the balcklist

It's in the `use-graphcool` branch I worked on, take a look at this:

https://github.com/spences10/100DaysOfCode-twitter-bot/blob/750b2c86ee69e4c999a526c830598e7e783ea1d7/src/helpers/dbHandleSentiment.js#L8

Thanks

**Comment by spences10** [comment]
@amandeepmittal referencing this for a fix here: https://github.com/spences10/twitter-bot-bootstrap/issues/127
