### ISSUE TITLE
Project of the day.

### ISSUE THREAD

**Issue by AlexandreResende** [freeCodeCamp/100DaysOfCode-twitter-bot#7]
It is a suggestion of a project that one can develop on that day. It can be a simple things of a skill to develop through that 1 hour.

**Comment by spences10** [comment]
This is a great idea and it looks like #3 and #4 have just been merged so I could play at adding in some random project like @Ilyes-Hammadi hase dome for #10

**Comment by spences10** [comment]
Should there be a hash tag to include for the project if the day and what time to tweet it?

**Comment by spences10** [comment]
Added #16 for this 👍

**Comment by amandeepmittal** [comment]
Done with #25

**Comment by spences10** [comment]
So, whilst doing the bins I think I have worked out how to do the controlled search.

Add each item to the leveldb as you search but before searching the string check the db if it there, if it is generate a new string, keep on going until there's no combinations left once that happens delete the db and start again 👍🔥🔥🔥🔥🔥👌

If you can't tell I'm quite happy to have mentally worked that out 😁😎
