### ISSUE TITLE
Use Zeit's Release

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#90]
Maybe consider pushing some tags to make a release for this?

https://github.com/zeit/release#usage

I'm not sure if I make a release on my branch if it will be reflected on the fCC one

**Comment by amandeepmittal** [comment]
Is it still up?

**Comment by spences10** [comment]
Yeah, I think??

**Comment by amandeepmittal** [comment]
I am closing this issue since we are still using Heroku, Feel free to re-open the issue if you want to shift to Zeis.
