### ISSUE TITLE
Promote the Slack Channel

### ISSUE THREAD

**Issue by spences10** [freeCodeCamp/100DaysOfCode-twitter-bot#97]
Is there a way to promote use of the Slack channel via the bot?

Maybe have it as one of the automated tweets?

Here is the signup link: https://t.co/yEbhWEtFsv

**Comment by amandeepmittal** [comment]
@spences10 we can use a cron job that implements the message after a particular period of time (let's say in 24 hours)?

**Comment by spences10** [comment]
I could probably add something to that effect and submit a PR

Or

You could add a help wanted and good first issue labels to it and see how that goes @amadeepmittal, what do you think?

Share the post via #100DaysOfCode on Twitter maybe?

**Comment by amandeepmittal** [comment]
@spences10 if you are interested in implementing a cron job, go ahead. Otherwise, let me know.
